name: Check PR - godot-annotation-processor
on:
  pull_request:
    paths:
      - 'plugins/godot-annotation-processor/**'
      - 'plugins/godot-entry-generator/**'
      - 'build.gradle.kts'
      - 'buildSrc/**'
      - 'gradle.properties'
      - 'settings.gradle.kts'
      - '.github/workflows/check-pr-annotation-processor.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: godot-annotation-processor:build -PignoreSamples