name: Check PR - godot-build-props
on:
  pull_request:
    paths:
      - 'utils/godot-build-props/**'
      - 'build.gradle.kts'
      - 'buildSrc/**'
      - 'gradle.properties'
      - '.github/workflows/check-pr-build-props.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: godot-build-props:build -PignoreSamples