name: CI
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  deploy_core:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: godot-library:bintrayUpload -PignoreSamples
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  deploy_build_props:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: godot-build-props:bintrayUpload -PignoreSamples
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  deploy_entry_generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: godot-entry-generator:bintrayUpload -PignoreSamples
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  deploy_annotation_processor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: godot-annotation-processor:bintrayUpload -PignoreSamples
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  deploy_compiler_plugin_common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: godot-compiler-plugin-common:bintrayUpload -PignoreSamples
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  deploy_compiler_plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: godot-compiler-plugin:bintrayUpload -PignoreSamples
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  deploy_compiler_native_plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: godot-compiler-native-plugin:bintrayUpload -PignoreSamples
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  deploy_godot_gradle_plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: godot-gradle-plugin:bintrayUpload -PignoreSamples
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}